# Generated by Django 2.1.2 on 2018-11-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fCost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fPic',
            field=models.CharField(max_length=25),
        ),
    ]
