# Generated by Django 2.1.2 on 2018-11-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0002_auto_20181117_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fPic',
            field=models.CharField(max_length=255),
        ),
    ]
