# Generated by Django 2.1.4 on 2018-12-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0003_auto_20181227_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eName',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
