# Generated by Django 2.1.2 on 2018-11-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0003_auto_20181117_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fPic',
            field=models.ImageField(upload_to='OrderMedel/'),
        ),
    ]
