# Generated by Django 2.1.2 on 2018-11-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0005_auto_20181117_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fPic',
            field=models.ImageField(upload_to='OrderMedel/'),
        ),
    ]
