# Generated by Django 2.1.2 on 2018-11-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0006_auto_20181117_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mDate', models.DateField()),
                ('bre', models.CharField(max_length=255)),
                ('lun', models.CharField(max_length=255)),
                ('din', models.CharField(max_length=255)),
            ],
        ),
    ]
