# Generated by Django 2.1.2 on 2018-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0007_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fName',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mDate',
            field=models.DateField(unique=True),
        ),
    ]
