# Generated by Django 2.1.2 on 2018-11-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0008_auto_20181122_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eId', models.IntegerField(unique=True)),
                ('uName', models.CharField(max_length=50)),
                ('uPwd', models.CharField(max_length=50)),
                ('flag', models.IntegerField(max_length=1)),
            ],
        ),
    ]
