# Generated by Django 2.1.2 on 2018-11-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='flag',
            field=models.IntegerField(),
        ),
    ]
