# Generated by Django 2.1.2 on 2018-11-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0011_auto_20181124_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='eId',
            field=models.CharField(max_length=30, verbose_name='employee_id'),
        ),
    ]
