# Generated by Django 2.1.2 on 2018-11-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0012_auto_20181124_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eId', models.CharField(max_length=50)),
                ('oDate', models.DateField()),
                ('bre', models.BooleanField()),
                ('lun', models.BooleanField()),
                ('din', models.BooleanField()),
            ],
        ),
    ]
