# Generated by Django 2.1.2 on 2018-12-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModel', '0013_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='food',
            name='fCost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fDesc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fPic',
            field=models.ImageField(blank=True, null=True, upload_to='OrderMedel/'),
        ),
    ]
